{% set version = "1.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-etm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/etm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/etm/etm_{{ version }}.tar.gz
  sha256: fe75df23b986b885d8b4a11190b715f2e7b5e4063c0f63a29457cadb2abd79c3

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - libblas
    - r-base
    - r-rcpp >=0.11.4
    - r-rcpparmadillo
    - r-data.table
    - r-lattice
    - r-survival
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.11.4
    - r-rcpparmadillo
    - r-data.table
    - r-lattice
    - r-survival

test:
  commands:
    - $R -e "library('etm')"           # [not win]
    - "\"%R%\" -e \"library('etm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=etm
  license: MIT
  license_file: LICENSE
  summary: 'The etm (empirical transition matrix) package permits to estimate the matrix of transition probabilities for any time-inhomogeneous multistate model with finite state space using the Aalen-Johansen estimator. Functions for data preparation and for displaying are also included (Allignol et al., 2011 <doi:10.18637/jss.v038.i04>).
    Functionals of the Aalen-Johansen estimator, e.g., excess length-of-stay in an intermediate state, can also be computed (Allignol et al. 2011 <doi:10.1007/s00180-010-0200-x>). '
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: etm
# Type: Package
# Title: Empirical Transition Matrix
# Version: 1.0.4
# Author: Arthur Allignol
# Description: The etm (empirical transition matrix) package permits to estimate the matrix of transition probabilities for any time-inhomogeneous multistate model with finite state space using the Aalen-Johansen estimator. Functions for data preparation and for displaying are also included (Allignol et al., 2011 <doi:10.18637/jss.v038.i04>). Functionals of the Aalen-Johansen estimator, e.g., excess length-of-stay in an intermediate state, can also be computed (Allignol et al. 2011 <doi:10.1007/s00180-010-0200-x>).
# Maintainer: Arthur Allignol <arthur.allignol@gmail.com>
# License: MIT + file LICENSE
# Depends: R (>= 3.0.0)
# Imports: survival, lattice, data.table, Rcpp (>= 0.11.4)
# Suggests: ggplot2, kmi, geepack
# LinkingTo: Rcpp, RcppArmadillo
# NeedsCompilation: yes
# Packaged: 2018-07-11 19:24:14 UTC; arthur
# Repository: CRAN
# Date/Publication: 2018-07-11 20:10:04 UTC
